agent:
  data: D:\\Workspaces\\Ziyunix


mqtt:
  broker:
    domain: MQTT连接地址
    mqtt: 2883
    wss: 443
  options:
    username: 1/storezhang
    password: MQTT密码
    clientid: ${HOSTNAME}
    keepalive: 5s
